development:
  adapter: mysql
  server: localhost
  username: root 
  password:
  database: teambox2
  
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  server: localhost
  username: root 
  password:
  database: teambox2_production
