development:
  adapter: mysql
  host: localhost
  username: root 
  password:
  database: teambox2
  
test: &TEST
  adapter: mysql
  host: localhost
  username: root 
  password:
  database: teambox2_test

production:
  adapter: mysql
  host: localhost
  username: root 
  password:
  database: teambox2_production

cucumber:
  <<: *TEST