#
# This file takes care of some key strings for the interface and app.
# You will also need to edit environment.rb with your own email settings.
# 

# This block defines defaults, shared for all environments.
# You can override them individually under development, test or production.
defaults: &DEFAULTS
  # The domain from where your app is served from.
  app_domain: app.teambox.com
  
  # Configuration for outgoing mail
  # By default, will send emails in production mode but not in development.
  allow_outgoing_email: true
  outgoing:
    from: yourapp.com           # the domain your emails will come from, as in no_reply@app.teambox.com
    host: localhost             # the actual SMTP server used to deliver emails. can be a local or remote server
    user: username
    pass: password
    auth: plain                 # choose: plain, login, cram_md5    
    port: 25
  
  # Set allow to true to allow the "reply to" feature for notifications.
  # This will allow users to post answers and comments by email.
  # When set to true, "reply above this line" notice will be displayed where relevant and accept emails.
  # You will need to set up:
  # * A catch-all address for email received for any username of the incoming mail server.
  # * A cron job to run script/inbox periodically to get email.
  allow_incoming_email: false
  incoming:
    host: 
    user:
    pass:

  # This links are used in the navigation bar for login and in every page's footer
  home_url: http://www.teambox.com
  tour_url: http://www.teambox.com/tour
  blog_url: http://blog.teambox.com
  help_url: http://help.teambox.com/faqs/using-teambox
  support_url: http://help.teambox.com
  
  # [NOT IMPLEMENTED]
  # If false, the only way of having an account will be being invited by another user.
  allow_signups: true
  
  # Address where your users should write to ask for help. Accepts an email or website.
  support: http://help.teambox.com
  
  time_zone: UTC

development:
  <<: *DEFAULTS
  app_domain: localhost:3000
  allow_outgoing_email: false

production:
  <<: *DEFAULTS
  app_domain: app.teambox.com

test: &TEST
  <<: *DEFAULTS
  app_domain: 127.0.0.1
  allow_outgoing_email: false

cucumber:
  <<: *TEST  
