#
# Main configuration file for functionality of a Teambox app instance.
#

# Configuration shared between all environments:
defaults: &defaults
  # The domain from where your app is served
  app_domain: app.teambox.com

  # How many activities should activity feeds display?
  activities_per_page: 25
  autorefresh_interval: 60 # in seconds

  daily_task_reminder_email_time: "06:00"

  # Set to true to use S3 storage instead of local filesystem storage.
  # Configure your access keys in amazon_s3.yml
  amazon_s3: false

  asset_max_file_size: 50 # in megabytes

  # If signups are disabled, the only way to create an account will be being invited
  # by another user. If there are no users in the system, you will be asked to
  # create the first one.
  allow_signups: true

  # Enable user groups
  allow_groups: true

  # Enable time tracking
  allow_time_tracking: true

  # Default timezone
  time_zone: UTC

  # Default language in which the app is displayed.
  # See translations in "config/locales/"
  default_locale: :en

  # By default, emails are sent in production but not in development
  allow_outgoing_email: true

  # Configuration for outgoing mail
  smtp_settings:
    :domain:         teambox.com   # the domain your emails will come from
    :address:        localhost     # SMTP server used to send emails
    :port:           25
    :user_name:      USER
    :password:       PWD
    :authentication: :plain        # options: plain, login, cram_md5

    # Set to true when using Gmail
    :enable_starttls_auto: false

    # Set to true if you have Net::SMTPSyntaxError errors when sending email.
    # Rails has sometimes a problem when sending email from "Name <address@host.com>".
    # If you are having problems sending email and your host is correctly configured,
    # try setting safe_from to true. You may need to create a user account for no-reply@yourapp.com
    :safe_from: false

  # Set allow to true to allow the "reply to" feature for notifications.
  # This will allow users to post answers and comments by email.
  # When set to true, "reply above this line" notice will be displayed where relevant and accept emails.
  allow_incoming_email: false

  # You will need to:
  # * Setup catch-all address for email received for any username of the incoming mail server.
  # * Run './script/inbox' periodically from cron to process incoming emails.
  incoming_email_settings:
    :type:      pop
    :server:    EXAMPLE.COM
    :username:  USER
    :password:  PWD

  # Destination where your users could write to ask for help. Accepts an email or website.
  support: http://help.teambox.com

  # These links are used for the login page. Delete a line to remove the link from the interface.
  home_url: http://www.teambox.com
  tour_url: http://www.teambox.com/tour
  users_url: http://www.teambox.com/testimonials
  services_url: http://www.teambox.com/services
  community_url: http://www.teambox.com/community
  blog_url: http://blog.teambox.com
  help_url: http://help.teambox.com/faqs/using-teambox
  support_url: http://help.teambox.com
  privacy_url: http://www.teambox.com/privacy
  terms_url: http://www.teambox.com/terms

development:
  <<: *defaults
  app_domain: localhost:3000
  allow_outgoing_email: false

production:
  <<: *defaults

test: &test
  <<: *defaults
  app_domain: 127.0.0.1
  allow_outgoing_email: false
  asset_max_file_size: 1

cucumber:
  <<: *test
